import * as Yup from 'yup';
// ----------------------------------------------------------------------

export const useUnitEditFormSchema = Yup.object().shape({
    txtTag: Yup.string().required('This field is required!'),
    txbQty: Yup.number().required('This field is required!'),
    ddlLocationId: Yup.number().required('This field is required!'),
    ddlOrientationId: Yup.number().required('This field is required!'),
    ddlUnitTypeId: Yup.number().required('This field is required!'),
    ddlControlsPreferenceId: Yup.number().required('This field is required!'),
    txbSummerSupplyAirCFM: Yup.number().required('This field is required!'),
    txbSummerReturnAirCFM: Yup.number().required('This field is required!'),
    txbSupplyAirESP: Yup.number().required('This field is required!'),
    txbExhaustAirESP: Yup.number().required('This field is required!'),
    ddlUnitModelId: Yup.number().required('This field is required!'),
    ddlUnitVoltageId: Yup.number().required('This field is required!'),
    txbAltitude: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirDB: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirWB: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirRH: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirDB: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirWB: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirRH: Yup.number().required('This field is required!'),
    txbSummerReturnAirDB: Yup.number().required('This field is required!'),
    txbSummerReturnAirWB: Yup.number().required('This field is required!'),
    txbSummerReturnAirRH: Yup.number().required('This field is required!'),
    txbWinterReturnAirDB: Yup.number().required('This field is required!'),
    txbWinterReturnAirWB: Yup.number().required('This field is required!'),
    txbWinterReturnAirRH: Yup.number().required('This field is required!'),
    txbWinterPreheatSetpointDB: Yup.number().required('This field is required!'),
    txbSummerCoolingSetpointDB: Yup.number().required('This field is required!'),
    txbSummerCoolingSetpointWB: Yup.number().required('This field is required!'),
    txbWinterHeatingSetpointDB: Yup.number().required('This field is required!'),
    txbSummerReheatSetpointDB: Yup.number().required('This field is required!'),
    ddlOA_FilterModelId: Yup.number().required('This field is required!'),
    ddlRA_FilterModelId: Yup.number().required('This field is required!'),
    ddlPreheatCompId: Yup.number().required('This field is required!'),
    ddlHeatExchCompId: Yup.number().required('This field is required!'),
    ddlCoolingCompId: Yup.number().required('This field is required!'),
    ddlHeatingCompId: Yup.number().required('This field is required!'),
    txbOA_FilterPD: Yup.number().required('This field is required!'),
    txbRA_FilterPD: Yup.number().required('This field is required!'),
    ddlReheatCompId: Yup.number().required('This field is required!'),
    ddlDamperAndActuatorId: Yup.number().required('This field is required!'),
    ddlElecHeaterVoltageId: Yup.number().required('This field is required!'),
    ddlPreheatElecHeaterInstallationId: Yup.number().required('This field is required!'),
    ddlHeatElecHeaterInstallationId: Yup.number().required('This field is required!'),
    ddlPreheatCoilHandingId: Yup.number().required('This field is required!'),
    ddlCoolingCoilHandingId: Yup.number().required('This field is required!'),
    ddlHeatingCoilHandingId: Yup.number().required('This field is required!'),
    ddlValveTypeId: Yup.number().required('This field is required!'),
    txbPreheatHWC_Cap: Yup.number(),
    txbPreheatHWC_FlowRate: Yup.number(),
    txbCoolingCWC_Cap: Yup.number(),
    txbCoolingCWC_FlowRate: Yup.number(),
    txbHeatingHWC_Cap: Yup.number(),
    txbHeatingHWC_FlowRate: Yup.number(),
    txbReheatHWC_Cap: Yup.number(),
    txbReheatHWC_FlowRate: Yup.number(),
    ddlCoolingFluidTypeId: Yup.number().required('This field is required!'),
    ddlCoolingFluidConcentrationId: Yup.number().required('This field is required!'),
    txbCoolingFluidEntTemp: Yup.number().required('This field is required!'),
    txbCoolingFluidLvgTemp: Yup.number().required('This field is required!'),
    txbRefrigSuctionTemp: Yup.number().required('This field is required!'),
    txbRefrigLiquidTemp: Yup.number().required('This field is required!'),
    txbRefrigSuperheatTemp: Yup.number().required('This field is required!'),
    ddlHeatingFluidTypeId: Yup.number().required('This field is required!'),
    ddlHeatingFluidConcentrationId: Yup.number().required('This field is required!'),
    txbHeatingFluidEntTemp: Yup.number().required('This field is required!'),
    txbHeatingFluidLvgTemp: Yup.number().required('This field is required!'),
    txbRefrigCondensingTemp: Yup.number().required('This field is required!'),
    txbRefrigVaporTemp: Yup.number().required('This field is required!'),
    txbRefrigSubcoolingTemp: Yup.number().required('This field is required!'),
    txbPercentCondensingLoad: Yup.number().required('This field is required!'),
    txbUnitHeightText: Yup.number().required('This field is required!'),
    txbUnitLengthText: Yup.number().required('This field is required!'),
    txbUnitWeightText: Yup.number().required('This field is required!'),
    txbUnitWidthText: Yup.number().required('This field is required!'),
    ddlHandingId: Yup.number().required('This field is required!'),
    ddlSupplyAirOpeningId: Yup.number().required('This field is required!'),
    ddlSupplyAirOpeningText: Yup.string().required('This field is required!'),
    ddlExhaustAirOpeningId: Yup.number().required('This field is required!'),
    ddlExhaustAirOpeningText: Yup.string().required('This field is required!'),
    ddlOutdoorAirOpeningId: Yup.number().required('This field is required!'),
    ddlOutdoorAirOpeningText: Yup.string().required('This field is required!'),
    ddlReturnAirOpeningId: Yup.number().required('This field is required!'),
    ddlReturnAirOpeningText: Yup.string().required('This field is required!'),
  });